### ISSUE TITLE
Missing Images in Milestone 2

### ISSUE THREAD

**Issue by pgysbers** [UBC-MDS/525_group18#20]
Hey group 18, please upload a corrected version of the Milestone2 notebook, I can't see your screenshots!

**Comment by deepaksidhu** [comment]
Hello Peter, thank you alerting us about this. It's totally my fault, for I change the structure of the images and notebooks for milestone 3, hence it altered the links to images for milestone 2. Sorry for the inconvenience.

This is the update link to the Milestone2 notebook,

https://github.com/UBC-MDS/525_group18/blob/main/notebooks/Milestone2/Milestone2.ipynb

**Comment by pgysbers** [comment]
Thanks, I looked at the files found in `/imgs` at the `0.0.2` tag
